import { domains, googleApiConfigs, users } from "../stores/mockData";

export const resources = {
  users: {
    title: "Data Users",
    description: "Management of Data Users (PIC)",
    path: "/users",
    singular: "User",
    searchPlaceholder: "Cari data...",
    columns: [
      ["name", "Nama PIC"],
      ["username", "Username"],
      ["email", "Email"],
      ["role", "Role"],
      ["telegramChatId", "Telegram ID"],
    ],
    fields: [
      { name: "name", label: "Nama", required: true },
      { name: "username", label: "Username", required: true },
      { name: "email", label: "Email Address", type: "email", required: true },
      { name: "role", label: "Role", type: "select", options: ["admin", "user", "Advertiser"], required: true },
      { name: "telegramChatId", label: "Telegram Chat ID" },
    ],
  },
  domains: {
    title: "Data Domains",
    description: "Management of Data Domains",
    path: "/domains",
    singular: "Domain",
    columns: [
      ["domainUrl", "URL Domain"],
      ["networkCode", "Kode Jaringan"],
      ["status", "Status"],
    ],
    fields: [
      { name: "domainUrl", label: "Domain URL", required: true },
      { name: "userOwner", label: "User Pemilik", type: "select", options: users.map((item) => item.name), required: true },
      { name: "networkCode", label: "Kode Jaringan (AdX)", required: true },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"], required: true },
    ],
  },
  subDomains: {
    title: "Data Sub Domains",
    description: "Kelola sub domain beserta PIC pemiliknya",
    path: "/sub-domains",
    singular: "Sub Domain",
    searchPlaceholder: "Cari subdomain, domain, atau PIC...",
    columns: [
      ["name", "Sub Domain"],
      ["parentDomain", "Domain Induk"],
      ["pic", "PIC / User"],
      ["status", "Status"],
    ],
    fields: [
      { name: "name", label: "Subdomain Lengkap", required: true },
      { name: "parentDomain", label: "Pilih Domain Induk", type: "select", options: domains.map((item) => item.domainUrl), required: true },
      { name: "pic", label: "PIC / User Pemilik", type: "select", options: ["-- Tidak ada / Pilih PIC --", ...users.map((item) => item.name)] },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"], required: true },
    ],
  },
  whitelists: {
    title: "Data Whitelists",
    description: "Management of Data Whitelists",
    path: "/whitelists",
    singular: "Whitelist",
    searchPlaceholder: "Cari data...",
    columns: [
      ["name", "Label"],
      ["url", "URL / Domain"],
      ["status", "Status"],
    ],
    fields: [
      { name: "name", label: "Label", required: true },
      { name: "url", label: "URL / Domain", required: true },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"], required: true },
    ],
  },
  adAccounts: {
    title: "Data Ad Accounts",
    description: "Management of Meta ad accounts",
    path: "/ad-accounts",
    singular: "Ad Account",
    searchPlaceholder: "Cari data...",
    columns: [
      ["name", "Nama Akun Ads"],
      ["actId", "ACT ID Meta"],
    ],
    fields: [
      { name: "name", label: "Nama Akun", required: true },
      { name: "actId", label: "Act ID Meta", required: true },
    ],
  },
  adsenseAccounts: {
    title: "Data Adsense Accounts",
    description: "Management of Adsense accounts",
    path: "/adsense-accounts",
    singular: "Adsense Account",
    searchPlaceholder: "Cari data...",
    columns: [
      ["name", "Nama Domain"],
      ["publisherId", "ID Publisher"],
      ["status", "Status Akun"],
      ["emailAkun", "Email Akun"],
      ["passwordAkun", "Pass Akun"],
      ["totalPayout", "Total Payout"],
      ["googleCredential", "Google A"],
      ["kodeCustomer", "Kode Customer"],
      ["nomorHp", "Nomor HP"],
      ["emailPemulihan", "Email Pemulihan"],
      ["negara", "Negara"],
      ["expDomain", "EXP Domain"],
      ["emailDomain", "Email Domain"],
      ["passwordDomain", "Pass Domain"],
      ["server", "Server"],
      ["usernameWp", "Username WP"],
      ["passwordWp", "Password WP"],
      ["saldo", "Saldo"],
      ["namaRekening", "Nama Di Rekening"],
      ["noRekening", "No Rekening"],
      ["networkCode", "Kode Jaringan"],
    ],
    fields: [
      { name: "name", label: "Nama Domain", required: true },
      { name: "publisherId", label: "Publisher ID", required: true },
      { name: "googleCredential", label: "Koneksi Google API", type: "select", options: googleApiConfigs.map((item) => item.name) },
      { name: "status", label: "Status", required: true },
      { name: "emailAkun", label: "Email Akun", type: "email" },
      { name: "passwordAkun", label: "Password Akun", type: "password" },
      { name: "totalPayout", label: "Total Payout" },
      { name: "kodeCustomer", label: "Kode Customer" },
      { name: "nomorHp", label: "Nomor HP" },
      { name: "emailPemulihan", label: "Email Pemulihan" },
      { name: "expDomain", label: "EXP Domain (Y-m-d)" },
      { name: "server", label: "Server" },
      { name: "saldo", label: "Saldo" },
      { name: "namaRekening", label: "Nama Rekening" },
      { name: "noRekening", label: "No Rekening" },
      { name: "networkCode", label: "Kode Jaringan" },
    ],
  },
  googleApiConfigs: {
    title: "Google API Credentials",
    description: "Management of Google API credentials",
    path: "/google-api-configs",
    singular: "Google Credential",
    columns: [
      ["name", "Nama Akun/Client"],
      ["clientId", "Client ID"],
      ["status", "Status Koneksi"],
    ],
    fields: [
      { name: "name", label: "Nama Kredensial / Pemilik", required: true },
      { name: "clientId", label: "Google Client ID", required: true },
      { name: "clientSecret", label: "Google Client Secret", type: "password", required: true },
      { name: "status", label: "Status Koneksi", type: "select", options: ["Connected", "Disconnected"], required: true },
    ],
  },
};
